name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "10.0.x"

    - name: Restore dependencies
      run: dotnet restore ./src/STYME/STYME.csproj

    - name: Build
      run: dotnet build ./src/STYME/STYME.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test ./src/STYME.UnitTests/STYME.UnitTests.csproj --configuration Release --no-build --verbosity normal
