name: Publish

on:
  push:
    tags: [ "v*" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "10.0.x"

    - name: Restore dependencies
      run: dotnet restore ./src/STYME/STYME.csproj

    - name: Build
      run: dotnet build ./src/STYME/STYME.csproj --configuration Release --no-restore

    - name: Pack
      run: dotnet pack ./src/STYME/STYME.csproj --configuration Release --no-build -o ./artifacts

    - name: Publish to NuGet
      run: dotnet nuget push ./artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
